import {StudentDataResDto} from "../../api/reponse-dto/student.res.dto";
import {PeriodLabel} from "../../api/enums";

export const mockStudentData: StudentDataResDto = {
    studentId: 15,
    studentName: "Wiem Cherif",
    semesterId: 1,
    semesterName: "Semestre 1",
    grades: [
        // Semestre 1
        {
            id: 1,
            createdDate: "2024-01-15",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 101,
            subjectName: "INTRODUCTION TO SOFTWARE ENGINEERING",
            subjectCode: "ICT201",
            semesterId: 1,
            semesterName: "Semestre 1",
            value: 25,
            type: "CC_1",
            periodLabel: "CC_1",
            comments: "",
            enteredBy: 1,
            enteredByName: "Prof. Martin",
            passed: false,
            creditsEarned: 5
        },
        {
            id: 2,
            createdDate: "2024-02-20",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 101,
            subjectName: "INTRODUCTION TO SOFTWARE ENGINEERING",
            subjectCode: "ICT201",
            semesterId: 1,
            semesterName: "Semestre 1",
            value: 45,
            type: "SN_1",
            periodLabel: "SN_1",
            comments: "",
            enteredBy: 1,
            enteredByName: "Prof. Martin",
            passed: true,
            creditsEarned: 5
        },
        {
            id: 3,
            createdDate: "2024-01-18",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 102,
            subjectName: "DATABASE SYSTEMS",
            subjectCode: "ICT202",
            semesterId: 1,
            semesterName: "Semestre 1",
            value: 28,
            type: "CC_1",
            periodLabel: "CC_1",
            comments: "",
            enteredBy: 2,
            enteredByName: "Prof. Dubois",
            passed: false,
            creditsEarned: 6
        },
        {
            id: 4,
            createdDate: "2024-02-22",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 102,
            subjectName: "DATABASE SYSTEMS",
            subjectCode: "ICT202",
            semesterId: 1,
            semesterName: "Semestre 1",
            value: 35,
            type: "SN_1",
            periodLabel: "SN_1",
            comments: "",
            enteredBy: 2,
            enteredByName: "Prof. Dubois",
            passed: true,
            creditsEarned: 6
        },
        // Semestre 2
        {
            id: 5,
            createdDate: "2024-03-10",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 103,
            subjectName: "COMPUTER NETWORKS",
            subjectCode: "ICT203",
            semesterId: 2,
            semesterName: "Semestre 2",
            value: 22,
            type: "CC_2",
            periodLabel: "CC_2",
            comments: "",
            enteredBy: 3,
            enteredByName: "Prof. Laurent",
            passed: false,
            creditsEarned: 5
        },
        {
            id: 6,
            createdDate: "2024-04-15",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 103,
            subjectName: "COMPUTER NETWORKS",
            subjectCode: "ICT203",
            semesterId: 2,
            semesterName: "Semestre 2",
            value: 50,
            type: "SN_2",
            periodLabel: "SN_2",
            comments: "",
            enteredBy: 3,
            enteredByName: "Prof. Laurent",
            passed: true,
            creditsEarned: 5
        },
        {
            id: 7,
            createdDate: "2024-03-12",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 104,
            subjectName: "WEB DEVELOPMENT",
            subjectCode: "ICT205",
            semesterId: 2,
            semesterName: "Semestre 2",
            value: 27,
            type: "CC_2",
            periodLabel: "CC_2",
            comments: "",
            enteredBy: 4,
            enteredByName: "Prof. Bernard",
            passed: false,
            creditsEarned: 5
        },
        {
            id: 8,
            createdDate: "2024-04-18",
            lastModifiedDate: null,
            studentId: 15,
            studentName: "Wiem Cherif",
            subjectId: 104,
            subjectName: "WEB DEVELOPMENT",
            subjectCode: "ICT205",
            semesterId: 2,
            semesterName: "Semestre 2",
            value: 48,
            type: "SN_2",
            periodLabel: "SN_2",
            comments: "",
            enteredBy: 4,
            enteredByName: "Prof. Bernard",
            passed: true,
            creditsEarned: 5
        }
    ],
    gpa: 14.5,
    status: "EN_COURS",
    firstName: "Wiem",
    lastName: "Cherif",
    email: "wiem.cherif@student.university.com",
    username: "STU2023015",
    role: "STUDENT",
    level: "LEVEL2",
    subjects: [
        {
            id: 101,
            name: "INTRODUCTION TO SOFTWARE ENGINEERING",
            code: "ICT201",
            credits: 5,
            description: null,
            active: null,
            level: null,
            cycle: null,
            semesterId: 1,
            semesterName: "Semestre 1",
            departmentId: null,
            departmentName: null,
            teacherId: null,
            teacherName: null,
            createdDate: null,
            lastModifiedDate: null
        },
        {
            id: 102,
            name: "DATABASE SYSTEMS",
            code: "ICT202",
            credits: 6,
            description: null,
            active: null,
            level: null,
            cycle: null,
            semesterId: 1,
            semesterName: "Semestre 1",
            departmentId: null,
            departmentName: null,
            teacherId: null,
            teacherName: null,
            createdDate: null,
            lastModifiedDate: null
        },
        {
            id: 103,
            name: "COMPUTER NETWORKS",
            code: "ICT203",
            credits: 5,
            description: null,
            active: null,
            level: null,
            cycle: null,
            semesterId: 2,
            semesterName: "Semestre 2",
            departmentId: null,
            departmentName: null,
            teacherId: null,
            teacherName: null,
            createdDate: null,
            lastModifiedDate: null
        },
        {
            id: 104,
            name: "WEB DEVELOPMENT",
            code: "ICT205",
            credits: 5,
            description: null,
            active: null,
            level: null,
            cycle: null,
            semesterId: 2,
            semesterName: "Semestre 2",
            departmentId: null,
            departmentName: null,
            teacherId: null,
            teacherName: null,
            createdDate: null,
            lastModifiedDate: null
        }
    ]
};