import { TeacherGradeResDto } from "../../api/reponse-dto/grade.res.dto";

export const mockStudents: TeacherGradeResDto[] = [
    {
        id: 1,
        studentId: 1,
        studentName: "Dupont Jean",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 15,
        type: "ASSIGNMENT",
        periodLabel: "CC1",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 2,
        studentId: 2,
        studentName: "Martin Sophie",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 12,
        type: "ASSIGNMENT",
        periodLabel: "CC1",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 3,
        studentId: 3,
        studentName: "Bernard Pierre",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 18,
        type: "EXAM",
        periodLabel: "SN1",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 4,
        studentId: 4,
        studentName: "Petit Marie",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 14,
        type: "EXAM",
        periodLabel: "SN1",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 5,
        studentId: 5,
        studentName: "Durand Thomas",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 16,
        type: "ASSIGNMENT",
        periodLabel: "CC2",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
    {
        id: 6,
        studentId: 6,
        studentName: "Leroy Camille",
        subjectId: 1,
        subjectName: "Mathématiques",
        subjectCode: "MATH101",
        semesterId: 1,
        semesterName: "Semestre 1",
        value: 11,
        type: "EXAM",
        periodLabel: "SN2",
        comments: "Note de test",
        enteredBy: 1,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString()
    },
];

export const mockSubject = {
    id: 1,
    name: "Mathématiques",
    code: "MATH101",
    credits: 6,
    description: "Cours de mathématiques avancées",
    level: "LEVEL1",
    cycle: "BACHELOR"
};
