import { studentResDto } from "../../api/reponse-dto/user.res.dto";

export const FakeStudents: studentResDto[] = [
  {
    id: 1,
    firstName: "Alice",
    lastName: "Martin",
    email: "alice.martin@example.com",
    username: "alice.martin",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 14,
        sn: 15,
        semester: "s1",
      },
      {
        code: "INFO101",
        title: "Informatique",
        cc: 16,
        sn: 13,
        semester: "s1",
      },
      { code: "PHYS100", title: "Physique", cc: 13, sn: 17, semester: "s2" },
    ],
  },
  {
    id: 2,
    firstName: "Benoit",
    lastName: "Durand",
    email: "benoit.durand@example.com",
    username: "benoit.durand",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 12,
        sn: 14,
        semester: "s1",
      },
      { code: "CHIM101", title: "Chimie", cc: 15, sn: 16, semester: "s2" },
    ],
  },
  {
    id: 3,
    firstName: "Claire",
    lastName: "Lefevre",
    email: "claire.lefevre@example.com",
    username: "claire.lefevre",
    role: "STUDENT",
    topics: [
      {
        code: "INFO101",
        title: "Informatique",
        cc: 17,
        sn: 18,
        semester: "s1",
      },
      { code: "PHYS100", title: "Physique", cc: 11, sn: 12, semester: "s2" },
      { code: "CHIM101", title: "Chimie", cc: 13, sn: 15, semester: "s2" },
    ],
  },
  {
    id: 4,
    firstName: "David",
    lastName: "Petit",
    email: "david.petit@example.com",
    username: "david.petit",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 15,
        sn: 16,
        semester: "s1",
      },
      {
        code: "INFO101",
        title: "Informatique",
        cc: 14,
        sn: 13,
        semester: "s1",
      },
    ],
  },
  {
    id: 5,
    firstName: "Emma",
    lastName: "Roux",
    email: "emma.roux@example.com",
    username: "emma.roux",
    role: "STUDENT",
    topics: [
      { code: "PHYS100", title: "Physique", cc: 16, sn: 17, semester: "s2" },
      { code: "CHIM101", title: "Chimie", cc: 12, sn: 14, semester: "s2" },
    ],
  },
  {
    id: 6,
    firstName: "Florian",
    lastName: "Girard",
    email: "florian.girard@example.com",
    username: "florian.girard",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 13,
        sn: 12,
        semester: "s1",
      },
      {
        code: "INFO101",
        title: "Informatique",
        cc: 15,
        sn: 16,
        semester: "s1",
      },
      { code: "PHYS100", title: "Physique", cc: 10, sn: 11, semester: "s2" },
    ],
  },
  {
    id: 7,
    firstName: "Gaelle",
    lastName: "Lambert",
    email: "gaelle.lambert@example.com",
    username: "gaelle.lambert",
    role: "STUDENT",
    topics: [
      { code: "CHIM101", title: "Chimie", cc: 17, sn: 18, semester: "s2" },
      {
        code: "INFO101",
        title: "Informatique",
        cc: 13,
        sn: 15,
        semester: "s1",
      },
    ],
  },
  {
    id: 8,
    firstName: "Hugo",
    lastName: "Moreau",
    email: "hugo.moreau@example.com",
    username: "hugo.moreau",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 16,
        sn: 17,
        semester: "s1",
      },
      { code: "PHYS100", title: "Physique", cc: 12, sn: 13, semester: "s2" },
    ],
  },
  {
    id: 9,
    firstName: "Ines",
    lastName: "Faure",
    email: "ines.faure@example.com",
    username: "ines.faure",
    role: "STUDENT",
    topics: [
      {
        code: "INFO101",
        title: "Informatique",
        cc: 18,
        sn: 17,
        semester: "s1",
      },
      { code: "CHIM101", title: "Chimie", cc: 14, sn: 15, semester: "s2" },
    ],
  },
  {
    id: 10,
    firstName: "Julien",
    lastName: "Bernard",
    email: "julien.bernard@example.com",
    username: "julien.bernard",
    role: "STUDENT",
    topics: [
      {
        code: "MATH116",
        title: "Mathématiques appliquées",
        cc: 11,
        sn: 13,
        semester: "s1",
      },
      { code: "PHYS100", title: "Physique", cc: 15, sn: 16, semester: "s2" },
      { code: "CHIM101", title: "Chimie", cc: 13, sn: 14, semester: "s2" },
    ],
  },
];
